---
plugin: aws_ec2
aws_access_key: ****
aws_secret_key: ****

# hosts:
#   -  aws_region_eu_west_1 user=ubuntu
# user: ubuntu
# region: eu-west-1
# # ansible_ssh_private_key_file: /home/misaki/Ansible/myboomi.cer
# # ansible_python_interpreter: /usr/bin/python3
# group: my-security-group
# key_name: myboomi
# instance_type: t2.micro
# image: ami-00463ddd1036a8eb6

keyed_groups:
  - key: tags
    prefix: tag
  - prefix: instance_type
    key: instance_type
  - key: placement.region
    prefix: aws_region
  # - key: user
  #   prefix: user