---
plugin: aws_ec2
aws_access_key: ***
aws_secret_key: ***

keyed_groups:
  - key: tags
    prefix: tag
  - prefix: instance_type
    key: instance_type
  - key: placement.region
    prefix: aws_region
# filters:
#   tag:Name:
#     - MyCloud
  # - key: user
  #   prefix: user