---
- name: Create EC2 Instance
  hosts: localhost
  become_method: sudo
  connection: local
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: /home/misaki/Ansible/myboomi.cer
    ansible_python_interpreter: /usr/bin/python3
    region: eu-west-1
    group: my-security-group
    key_name: myboomi
    instance_type: t2.micro
    image: ami-00463ddd1036a8eb6

  vars_files:
    - vault.yml

  tasks:
  - name: Create a vpc
    ec2_vpc_net:
      region: "{{ region }}"
      name: my_vpc
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      cidr_block: 10.10.0.0/16
    register: vpc_info  